name: Build PHAR

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install Dependencies
        run: composer install

      - name: Generate PHAR file
        run: composer box compile

      - name: Upload PHAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/svgtinyps.phar
          asset_name: svgtinyps.phar
          asset_content_type: application/octet-stream
