name: Build binary for macOS arm64

on:
  release:
    types: [ created ]

  workflow_dispatch:

permissions: {}

env:
  BINARY_NAME: 'svgtinyps-macos-arm64'
  COMPILE_PHP_VERSION: "8.3"


jobs:
  build-macos-arm-binary:
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Install macOS missing packages and mark os suffix
        run: |
          brew install automake gzip
          echo "SPC_BUILD_OS=macos" >> $GITHUB_ENV

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
        with:
          php-version: ${{ env.COMPILE_PHP_VERSION }}
          tools: composer:v2

      - name: Cache build dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: build/
          key: build-deps-php${{ env.COMPILE_PHP_VERSION }}-${{ runner.os }}-${{ runner.arch }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer install
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Build Binary
        run: ./build.sh --name "${{ env.BINARY_NAME }}"

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Upload binaries
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.BINARY_NAME }}
          path: build/bin/${{ env.BINARY_NAME }}

      - if: ${{ github.event_name != 'workflow_dispatch' }}
        name: Upload binaries to release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v2.4.1
        with:
          files: build/bin/${{ env.BINARY_NAME }}
