name: Build binary for windows x86_64

on:
  release:
    types: [ created ]

  workflow_dispatch:

permissions: {}

env:
  BINARY_NAME: 'svgtinyps-windows-x86_64.exe'
  COMPILE_PHP_VERSION: "8.3"


jobs:
  build-windows-binary:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Cache build dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: build/
          key: build-deps-php${{ env.COMPILE_PHP_VERSION }}-${{ runner.os }}-${{ runner.arch }}

      - name: Get composer cache directory
        id: composer-cache
        run: |
          $dir = composer config cache-files-dir
          echo "dir=$dir" >> $env:GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**\\composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer install
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Build .phar
        run: composer box compile

      - name: Checkout static-php-cli
        working-directory: build
        shell: pwsh
        run: |
          if (Test-Path "static-php-cli") {
            Set-Location "static-php-cli"
            git pull origin main
          } else {
            git clone --depth 1 https://github.com/crazywhalecc/static-php-cli.git
          }

      - name: Composer update
        working-directory: build/static-php-cli/
        run: composer update --no-dev --classmap-authoritative

      - name: SPC doctor
        working-directory: build/static-php-cli/
        run: ./bin/spc doctor

      - name: SPC Download
        working-directory: build/static-php-cli/
        run: ./bin/spc download --with-php="${{ env.COMPILE_PHP_VERSION }}" --for-extensions="dom,phar,zlib" --prefer-pre-built

      - name: SPC Switch PHP version
        working-directory: build/static-php-cli/
        run: ./bin/spc switch-php-version "${{ env.COMPILE_PHP_VERSION }}"

      - name: SPC Build
        working-directory: build/static-php-cli/
        run: ./bin/spc build --build-micro "dom,phar,zlib"

      - name: PHP Micro combine
        working-directory: build/static-php-cli/
        run: ./bin/spc micro:combine "../bin/svgtinyps.phar" --output="../bin/${{ env.BINARY_NAME }}"

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Upload binaries
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ env.BINARY_NAME }}
          path: build/bin/${{ env.BINARY_NAME }}

      - if: ${{ github.event_name != 'workflow_dispatch' }}
        name: Upload binaries to release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.4.1
        with:
          files: build/bin/${{ env.BINARY_NAME }}
