name: Build binary for windows x86_64

on:
  release:
    types: [ created ]

  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BINARY_NAME: 'svgtinyps-windows-x86_64.exe'
  COMPILE_PHP_VERSION: "8.3"


jobs:
  build-windows-binary:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

#      - name: Cache build dependencies
#        uses: actions/cache@v4
#        with:
#          path: build/
#          key: build-deps-php${{ env.COMPILE_PHP_VERSION }}-${{ runner.os }}-${{ runner.arch }}

#      - name: Get composer cache directory
#        id: composer-cache
#        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
#
#      - name: Cache dependencies
#        uses: actions/cache@v4
#        with:
#          path: ${{ steps.composer-cache.outputs.dir }}
#          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
#          restore-keys: ${{ runner.os }}-composer-

      - name: Composer install
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - run: mkdir build

      - name: Checkout static-php-cli
        working-directory: build
        run: git clone --depth 1 https://github.com/crazywhalecc/static-php-cli.git

      - name: Composer update
        working-directory: build/static-php-cli/
        run: composer update --no-dev --classmap-authoritative

      - name: Check dependencies
        working-directory: build/static-php-cli/
        run: ./bin/spc doctor

#      - name: Build Binary
#        run: ./build.sh --name "${{ env.BINARY_NAME }}"
#
#      - if: ${{ github.event_name == 'workflow_dispatch' }}
#        name: Upload binaries
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ env.BINARY_NAME }}
#          path: build/bin/${{ env.BINARY_NAME }}
#
#      - if: ${{ github.event_name != 'workflow_dispatch' }}
#        name: Upload binaries to release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: build/bin/${{ env.BINARY_NAME }}
